apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-ssm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::127710927797:role/eks-ssm-prod-role
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  serviceAccountName: oidc-ssm
  containers:
    - name: debug
      image: 127710927797.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-parameter-store:latest
      imagePullPolicy: Always
      env:
        - name: PARAMS
          value: "prod.payment.cart_host prod.payment.cart_port prod.payment.user_port"
